### ISSUE TITLE
Error when handling nil object

### ISSUE THREAD

**Issue by sniperliu** [weavejester/impi#8]
I had some logic like below and encounter create-object error when pred is false.

```
{:pixi.container/children
 [view1
  (when (pred) view2)]
```
I also tried to add defmethod for nil, but there is another error regarding update cached properties.

Could you help?

**Comment by weavejester** [comment]
I'm not sure what you expect to happen. The `when` macro returns `nil` when the predicate is false. `nil` is not a valid Impi data structure.

If you want to omit the data structure when it is nil, you'll need to add some additional logic in. For example:

```clojure
{:pixi.container/children
 (into [view1] (if (pred) [view2])}
```

**Comment by sniperliu** [comment]
Thanks for your reply.

In our case, we want to use impi data structure to define our view, but some view should be conditionally rendered.

My point is whether we could make nil a valid object and safely ignored? So it's easier to add simple logic in view definition because we expect designers with minimum clojure knowledge to modify it.

Or you have better suggestion? I could make the change and put MR. Thanks in advance.

**Comment by weavejester** [comment]
You can manipulate the data structure in any way you want. If you're not dealing with rapid update you could walk the tree and remove any `nil` values in `pixi.container/children`. If you want something a little quicker then you can replace the vector with a function that removes `nil` values, e.g.

```clojure
{:pixi.container/children
 (remove-nils view1 (when (pred) view2))}
```

Or you could go further and write  a function that creates the container for you:

```clojure
(container view1 (when (pred) view2))
```

It's all just data manipulation, so how you approach the problem is up to you. However, I don't think it makes sense to ignore `nil` values *by default*. Better to let people choose that on a per-project basis.

**Comment by sniperliu** [comment]
Ya, totally agree that's per-project basis.
Thanks again.
